version: "3"
services:
  rails:
    build: ./docker/ruby
    container_name: forem_rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/forem
  db:
    image: postgres:13-alpine
    container_name: forem_postgresql
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: forem
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
  redis:
    image: redis:6.0.9-alpine
    container_name: forem_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
